source 'https://rubygems.org'

gem 'report_builder'
gem 'selenium-webdriver',        '3.14.0'
gem 'cucumber',                  '3.1.2'
gem 'rspec',                    '3.6.0'
gem 'capybara',                 '3.10.1'
gem 'rake'
gem 'faker'
gem 'cpf_faker'
gem 'brstring'
gem 'logger'
gem 'capybara-screenshot',       '1.0.22'
gem 'site_prism',               '3.0'
gem 'pry'
gem 'prawn',                      '2.1.0'
gem 'parallel_tests',              '2.7.0'
gem 'httparty'
gem 'mongo'
gem 'correios-cep'
gem 'brstring'
gem 'jsonpath'
